# Generated by Django 4.2.27 on 2026-01-05 15:34

import advisor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this connection', max_length=100)),
                ('host', models.TextField(help_text='Database host (encrypted)')),
                ('port', models.IntegerField(default=5432)),
                ('database', models.CharField(max_length=100)),
                ('username', models.TextField(help_text='Database username (encrypted)')),
                ('password', models.TextField(help_text='Database password (encrypted)')),
                ('ssl_mode', models.CharField(choices=[('disable', 'Disable'), ('allow', 'Allow'), ('prefer', 'Prefer'), ('require', 'Require'), ('verify-ca', 'Verify CA'), ('verify-full', 'Verify Full')], default='prefer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
            bases=(models.Model, advisor.models.EncryptedFieldMixin),
        ),
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_query', models.TextField(help_text='The original SQL query')),
                ('original_plan', models.JSONField(blank=True, help_text='EXPLAIN ANALYZE output as JSON', null=True)),
                ('original_execution_time', models.FloatField(blank=True, help_text='Execution time in milliseconds', null=True)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='advisor.connection')),
            ],
            options={
                'verbose_name_plural': 'Query histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('index', 'Add Index'), ('rewrite', 'Query Rewrite'), ('config', 'Configuration Change'), ('schema', 'Schema Change')], max_length=20)),
                ('description', models.TextField(help_text='Explanation of the optimization')),
                ('optimized_query', models.TextField(blank=True, help_text='Rewritten query if applicable', null=True)),
                ('suggested_indexes', models.JSONField(default=list, help_text='List of CREATE INDEX statements')),
                ('tested_execution_time', models.FloatField(blank=True, help_text='Tested execution time in ms', null=True)),
                ('improvement_percentage', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField(default=0, help_text='Ranking by improvement')),
                ('gemini_raw_response', models.JSONField(blank=True, help_text='Raw Gemini response for debugging', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='advisor.queryhistory')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
