# Generated by Django 4.2.27 on 2026-01-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryhistory',
            name='ai_provider',
            field=models.JSONField(blank=True, help_text='AI provider used for recommendations', null=True),
        ),
    ]
