# Generated by Django 4.2.27 on 2026-01-08 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_queryhistory_ai_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='password_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When password was last set'),
            preserve_default=False,
        ),
    ]
