# Generated by Django 4.2.27 on 2026-01-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_connection_password_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='tested_plan',
            field=models.JSONField(blank=True, help_text='Execution plan from testing', null=True),
        ),
    ]
