# Generated by Django 4.2.27 on 2026-01-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0004_recommendation_tested_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='all_indexes_applied',
            field=models.JSONField(blank=True, default=list, help_text='All indexes created across iterations', null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='final_optimized_query',
            field=models.TextField(blank=True, help_text='Final query after all iterations', null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='optimization_attempts',
            field=models.IntegerField(default=1, help_text='Number of optimization iterations'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='query_was_rewritten',
            field=models.BooleanField(default=False, help_text='Whether query was modified from original'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='seq_scan_eliminated',
            field=models.BooleanField(default=False, help_text='Whether seq scan was eliminated'),
        ),
    ]
